- hosts: mproxy
  tasks:
    - name: Pull Mongo Proxy Image
      sudo: yes
      docker:
        image: "lgatica/mongos:latest"
        state: present

- hosts: mshard mconfig
  tasks:
    - name: Pull Mongo Config And Shard Image
      sudo: yes
      docker:
        image: "lgatica/mongod:latest"
        state: present

- hosts: mconfig
  tasks:
    - name: Setup Config Node
      sudo: yes
      docker:
        image: "lgatica/mongod:latest"
        name: "MongoConfig"
        expose:
          - 27017
        net: host
        restart_policy: always
        state: reloaded
        command: --configsvr --dbpath=/mongo/data
        volumes:
          - /mongo/data

- hosts: mproxy
  tasks:
    - name: Setup Proxy Node
      sudo: yes
      docker:
        image: "lgatica/mongos:latest"
        name: "MongoProxy"
        expose:
          - 27017
        net: host
        restart_policy: always
        state: reloaded
        command: --configdb "{{ groups['mconfig'] | join(':27017') }}"

- hosts: mshard
  tasks:
    - name: Setup Shard Node
      sudo: yes
      docker:
        image: "lgatica/mongod:latest"
        name: "MongoConfig"
        expose:
          - 27017
        net: host
        restart_policy: always
        state: reloaded
        command: --shardsvr --dbpath=/mongo/data
        volumes:
          - /mongo/data